spring:
  application:
    name: "nft"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/web3?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  redis:
    database: 0 #索引
    host: 127.0.0.1
    port: 6379
    #    password: root #修改成对应自己的redis密码
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接
        min-idle: 1 #最小空闲连接
  servlet:
    multipart:
      max-file-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cache:
   type: redis

server:
  port: 9966

web3j:
  blockchain_name: 测试私链
  blockchain_resources_name: 以太币
  private_key: 3cf44c4d4252d9d9277f5503dac4e365f56c69cff5d1396da4f156dc115ddcac
  gas_price: 293932
  gas_limit: 3000000
  admin-client: false
#  client-address: "https://opbningxia.bsngate.com:18602/api/cbec55bcc1aa422c9cd0e99ea100290e/rpc"
#  client-address: "http://127.0.0.1:7545"
  client-address: "http://192.168.1.250:8545"
  system_token_address : "0x1724A1D07dF5Dcc33E69fA87Eb547c305332923C"


ipfs:
  node_url: https://gateway.pinata.cloud/ipfs/
  pinata:
   pinata_api_key: 9e40984731568f062f21
   pinata_secret_api_key: c7e3a4f1a1cbeb977ff77739fd967a9ed277bd3e6ce1cf7224bdda3a072b3827

mybatis:
  type-aliases-package: com.example.web3study.pojo
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



google:
  recaptcha:
    key:
      site: 6LddJzEkAAAAAMX7_8cXpxmhqYlrBRUqPOCQjcX0
      secret: 6LddJzEkAAAAAMA2eKHrXYToqezjZopzBr68A98J