spring:
  application:
    name: "nft"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/web3?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
server:
  port: 9966

web3j:
  private_key: dc156b09431f68dec35e60d6a1882afdd787f22f416503264a580271e2c6acba
  gas_limit: 6721975
  admin-client: false
#  client-address: "https://opbningxia.bsngate.com:18602/api/cbec55bcc1aa422c9cd0e99ea100290e/rpc"
#  client-address: "http://127.0.0.1:7545"
  client-address: "http://192.168.1.250:8545"


ipfs:
  node_url: https://ipfs.io/ipfs/
  pinata:
   pinata_api_key: 9e40984731568f062f21
   pinata_secret_api_key: c7e3a4f1a1cbeb977ff77739fd967a9ed277bd3e6ce1cf7224bdda3a072b3827

mybatis:
  type-aliases-package: com.example.web3study.pojo


